services:
  - type: web
    name: foretagsboende
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CONTACT_EMAIL
        value: kontakt@bostadsuthyrning.se
      - key: LEAD_EMAIL
        value: kontakt@bostadsuthyrning.se
      - key: JWT_SECRET
        value: residence_studio_super_secret_jwt_key_2024
      - key: GUESTY_CLIENT_ID
        value: 0oatnyobvq6fqjH7y5d7
      - key: GUESTY_CLIENT_SECRET
        value: -pt2Motf-BxAoqCz2fxp54P5MkorEMRkCr7EVpfAkRK8Oz2sk8-Gzn3GeoraPzLr
